# Generated by Django 4.1.5 on 2023-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Total_jobs',
            field=models.FloatField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Total_parts',
            field=models.FloatField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
