# Generated by Django 4.1.5 on 2023-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf', '0003_alter_part_angle_plan_down_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Total_area',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='angle_plan_down',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='angle_plan_left',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='angle_plan_right',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='angle_plan_up',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='bend_down',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='bend_left',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='bend_right',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='bend_top',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='pop_revit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='screw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Total_jobs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Total_parts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
